groups:
- name: example
  rules:
  - alert: HighErrorRate
    expr: rate(http_requests_total{job="mysql-server"}[5m]) > 100
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High error rate detected"
      description: "The error rate is too high for the last 5 minutes."
